version: 2
registries:
  gravityforms:
    type: composer-repository
    url: https://gf-composer-proxy.arnaud-ritti.workers.dev/wordpress-muplugin/
    username: licensekey
    password: "${{secrets.ORG_GRAVITYFORMS_KEY}}"
  acf:
    type: composer-repository
    url: https://auth-acf-composer-proxy.pivvenit.net/wordpress-muplugin/
    username: licensekey
    password: "${{secrets.ORG_ACF_PRO_KEY}}"

updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "1.x"
    allow:
      - dependency-type: "direct"
    labels:
      - "composer"
      - "dependencies"
    commit-message:
      prefix: "fix"
      prefix-development: "build"
      include: "scope"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    registries:
      - acf
      - gravityforms

  - package-ecosystem: "npm"
    directory: "/web/app/themes/lumberjack"
    schedule:
      interval: "weekly"
    target-branch: "1.x"
    allow:
      - dependency-type: "direct"
    labels:
      - "npm"
      - "dependencies"
    commit-message:
      prefix: "fix"
      prefix-development: "build"
      include: "scope"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "1.x"
    allow:
      - dependency-type: "direct"
    labels:
      - "npm"
      - "dependencies"
    commit-message:
      prefix: "fix"
      prefix-development: "build"
      include: "scope"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "1.x"
    allow:
      - dependency-type: "direct"
    labels:
      - "github-actions"
      - "dependencies"
    commit-message:
      prefix: "ci"
      include: "scope"
