- name: npm
  color: fef2c0
- name: github-actions
  color: e99695
- name: composer
  color: bfe5bf
- name: dependencies
  color: b4a8d1
- name: direct
  color: 5319e7
- name: indirect
  color: eeeeee
- name: production
  color: ff7619
- name: development
  color: e99695
- name: security
  color: fbca04
