# Number of days of inactivity before an issue becomes stale
daysUntilStale: 90
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 7
# Issues with these labels will never be considered stale
exemptLabels:
  - pinned
  - security
# Label to use when marking an issue as stale
staleLabel: stale
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  Cette demande a été automatiquement libellée comme obsolète parce qu'il
  n'y a pas eu d'activité depuis plus de trois mois.
  Elle sera fermée dans une semaine si aucune autre activité n'a lieu.
  Merci pour vos contributions.
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: false
