#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

COLOR_RED=$(printf '\e[0;31m')
COLOR_DEFAULT=$(printf '\e[m')
ICON_CROSS=$(printf $COLOR_RED'✘'$COLOR_DEFAULT)

function __print_fail {
    echo "$ICON_CROSS $1"
}

function __is_binary {
    P=$(printf '%s\t-\t' -)
    T=$(git diff --no-index --numstat /dev/null "$1")

    case "$T" in "$P"*) return 0 ;; esac

    return 1
}

# Prevent commit on master
#CURRENT_BRANCH=$(git symbolic-ref HEAD)
#if [[ "$CURRENT_BRANCH" == "refs/heads/master" ]] || [[ "$CURRENT_BRANCH" == "refs/heads/main" ]]; then
#    __print_fail "Direct commits to the main branch are not allowed."
#    exit 1
#fi

# Prevent merge tag
MERGE_FILES=""
for FILE in $(git diff-index --name-only --diff-filter=ACM --cached HEAD --); do
    if egrep -rls "^<<<<<<< |^>>>>>>> $" "$FILE" > /dev/null; then
        if ! __is_binary "$FILE"; then
            MERGE_FILES="$MERGE_FILES\n      $FILE"
        fi
    fi
done

if [ "$MERGE_FILES" ]; then
    __print_fail "Merge markers found in:$MERGE_FILES"
    exit 1
fi

# Lint the staged files
npx lint-staged --relative
